import {analyze,plan,num,errors,ranges,tbwFactor,trend} from './clinical.js';
const defaults={duration:'unknown',volume:'unknown',drop:'8',flags:[]};let s={...defaults,flags:[]},logs=[],step=0;
const labels={na:'血清Na',weight:'體重',age:'年齡',glucose:'血糖',cr:'Creatinine',egfr:'eGFR',sbp:'收縮壓',k:'血鉀',ca:'總血鈣',uosm:'尿滲透壓 Uosm',urine:'24小時尿量',una:'尿Na',uk:'尿K',serumOsm:'實測血清滲透壓',factor:'TBW係數',insensible:'不顯性失水',giLoss:'腎外持續自由水流失',urineLoss:'尿液持續自由水流失',intake:'其他已提供自由水',drop:'首24小時下降目標'};
const flags=[['poorIntake','飲水不足／吞嚥或照護問題'],['gi','腹瀉／嘔吐／引流'],['fever','發燒／流汗／呼吸失水'],['osmotic','mannitol／高尿素負荷'],['sodium','高張NaCl／NaHCO₃／鈉負荷'],['lithium','鋰鹽或其他致腎性尿崩症藥物'],['diuretics','使用利尿劑'],['recovery','解除阻塞／AKI恢復期'],['brain','腦傷／腦部手術／下視丘病變']];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(x,d=1)=>x===null||x===undefined?'—':Number(x).toLocaleString('zh-TW',{maximumFractionDigits:d,minimumFractionDigits:d});
const field=(k,unit='',hint='')=>`<label class="field"><span>${labels[k]}</span><div class="input-wrap"><input data-key="${k}" id="${k}" type="number" inputmode="decimal" min="${ranges[k][0]}" max="${ranges[k][1]}" step="any" value="${esc(s[k])}" placeholder="請輸入" aria-describedby="${k}-hint">${unit?`<em>${unit}</em>`:''}</div><small class="hint" id="${k}-hint">${hint}</small></label>`;
const sel=(k,title,options)=>`<label class="field"><span>${title}</span><select data-key="${k}" id="${k}"><option value="">請選擇</option>${options.map(([v,t])=>`<option value="${v}" ${s[k]===v?'selected':''}>${t}</option>`).join('')}</select></label>`;
const radios=(k,title,options,hint='')=>`<fieldset><legend>${title}</legend><div class="choices">${options.map(([v,t])=>`<label class="choice"><input type="radio" name="${k}" data-key="${k}" value="${v}" ${s[k]===v?'checked':''}>${t}</label>`).join('')}</div>${hint?`<p class="hint">${hint}</p>`:''}</fieldset>`;
const note=(body,kind='')=>`<div class="notice ${kind}">${body}</div>`;
const next=()=>`<div class="actions">${step>0?'<button class="button secondary" data-nav="prev">上一步</button>':'<select class="demo-select" id="demo" aria-label="載入教學案例"><option value="">載入教學案例</option><option value="dehydration">攝水不足</option><option value="di">低張性多尿</option><option value="shock">休克合併高血鈉</option><option value="sodium">急性鈉負荷</option></select>'}${step<3?`<button class="button" data-nav="next">前往${['','原因分析','補水計畫','治療追蹤'][step+1]}</button>`:''}</div>`;
function first(){return `<h2 id="section-title">基本評估</h2><p class="intro">先確認急症、發生時間與容量狀態。</p><div class="grid">${field('na','mmol/L')}${field('weight','kg')}${field('age','歲')}${sel('sex','生理性別（TBW估算）',[['male','男性'],['female','女性']])}${field('glucose','mg/dL')}${field('cr','mg/dL')}${field('egfr','mL/min/1.73m²')}${field('sbp','mmHg')}${sel('renal','腎功能／AKI狀態',[['stable','穩定，無AKI且eGFR≥30'],['aki','AKI或腎功能正在變動'],['severe','eGFR<30／重度腎功能障礙'],['rrt','已接受透析／CRRT']])}</div>${radios('duration','高血鈉發生時間',[['unknown','不明'],['chronic','超過48小時'],['acute','48小時內']],'急性需有先前血鈉或明確事件佐證；時間不明採慢性起始策略。')}${radios('volume','容量狀態（臨床評估）',[['hypo','低血容量'],['eu','大致正常'],['hyper','容量過多'],['unknown','尚未確認']])}${radios('hemo','循環灌流',[['stable','已確認穩定'],['shock','低血壓／休克'],['unknown','尚未確認']])}${radios('neuro','新發神經症狀（意識改變／抽搐）',[['no','無'],['yes','有'],['unknown','尚未確認']])}${radios('intentional','是否為神經重症目標性高血鈉？',[['no','否'],['yes','是'],['unknown','尚未確認']])}${next()}`;}
function second(){return `<h2 id="section-title">原因分析</h2><p class="intro">結合尿液反應與病史，找出可處理的水分失衡來源。</p><div class="grid">${field('urine','mL/day','需有實際量測；0代表已確認無尿。')}${field('uosm','mOsm/kg')}${field('una','mmol/L')}${field('uk','mmol/L')}${field('k','mmol/L')}${field('ca','mg/dL','低白蛋白時需考慮游離鈣。')}${field('serumOsm','mOsm/kg','疑似檢驗偽差時有幫助。')}</div><fieldset><legend>病史與暴露因素（可複選）</legend><div class="checks">${flags.map(([k,t])=>`<label class="choice"><input type="checkbox" data-flag="${k}" ${s.flags.includes(k)?'checked':''}>${t}</label>`).join('')}</div></fieldset><div id="causes" class="result-list"></div>${next()}`;}
function third(){return `<h2 id="section-title">補水計畫</h2><p class="intro">先定矯正目標，再加入持續失水與既有給水。</p><div class="grid two">${sel('drop','首24小時下降目標',[['6','6 mmol/L'],['8','8 mmol/L（預設）'],['10','10 mmol/L']])}${field('factor','','選填；未填時依性別與年齡估算。')}</div><p class="hint" id="factorHint"></p><div id="waterMetrics"></div><h3 class="guide-title">持續流失與已提供水分</h3><p class="hint">以下輸入均為自由水等值，單位mL／24小時。尚未估算請留空；確認無流失才填0。</p><div class="grid two subgrid">${field('insensible','mL/day','由臨床估計，發燒／呼吸急促需調整。')}${field('giLoss','mL/day','腹瀉或引流總量不一定等於自由水量。')}${field('urineLoss','mL/day','可參考尿量與尿Na／K計算EFWC。')}${field('intake','mL/day','口服、管灌及其他輸液的自由水等值。')}</div><div id="efwcControl"></div>${radios('lossReviewed','上述流失與給水量已檢視？',[['yes','已檢視，可作暫定估算'],['no','尚未確認']],'尿液EFWC反映量測期間；尿量、DDAVP或利尿治療改變後需重新估算。')}${sel('route','擬採給水途徑',[['d5w','IV D5W'],['enteral','口服／管灌自由水'],['half','0.45% NaCl（需另計鈉與鉀）']])}<div id="planResult"></div>${next()}`;}
function fourth(){return `<h2 id="section-title">治療追蹤</h2><p class="intro">輸入實際採血時間與Na，檢查下降速度與持續流失。</p><div class="tracking-form"><div class="grid two"><label class="field"><span>起始Na採血時間（台灣）</span><div class="input-wrap"><input id="baselineTime" type="datetime-local" data-key="baselineTime" value="${esc(s.baselineTime)}"></div><small class="hint">起始Na使用基本評估的 ${esc(s.na||'尚未輸入')} mmol/L。</small></label><div class="readonly">治療初期／嚴重高血鈉：每2–4小時複測Na；同步監測血糖、K、尿量、灌流及神經狀態。</div><label class="field"><span>追蹤Na採血時間（台灣）</span><div class="input-wrap"><input id="logTime" type="datetime-local"></div></label><label class="field"><span>追蹤血清Na</span><div class="input-wrap"><input id="logNa" type="number" min="100" max="220" step="any" placeholder="請輸入"><em>mmol/L</em></div></label></div><div class="actions"><button id="addLog" class="button">加入追蹤</button><button id="now" class="quiet">填入目前台灣時間</button></div><p id="logError" class="feedback" role="alert"></p></div><div id="trendResult"></div><div id="clinicalReport"></div><div class="actions"><button class="button secondary" data-nav="prev">上一步</button><button class="button" id="print">列印評估摘要</button></div>`;}
function render(){document.querySelector('#steps').innerHTML=['基本評估','原因分析','補水計畫','治療追蹤'].map((t,i)=>`<button data-step="${i}" class="${i===step?'active':''}" ${i===step?'aria-current="step"':''}><span class="step-num">0${i+1}</span><span>${t}</span></button>`).join('');document.querySelector('#content').innerHTML=[first,second,third,fourth][step]();update();}
function treatment(a){if(!a.high)return '先確認血鈉是否>145 mmol/L。';if(s.hemo==='shock'||num(s,'sbp')!==null&&num(s,'sbp')<90)return '先以0.9% NaCl或平衡晶體液恢復灌流，反覆評估；循環穩定後才制定自由水補充計畫。';if(s.volume==='hypo')return '補足循環容量後，依鈉矯正目標補自由水；仍有鈉與水共同缺損時，可考慮0.45% NaCl並分別計算自由水。';if(s.volume==='hyper')return '停止過量鈉輸入；D5W補自由水配合排鈉／利尿。若少尿、肺水腫或無法容納補水，評估RRT。';if(s.volume==='eu')return '可用口服／管灌自由水（需確認吞嚥安全）或IV D5W；依實測Na、尿量與血糖調整。';return '先完成容量與灌流評估，再選給水方式。';}
function update(){
 const a=analyze(s),p=plan(s),bad=errors(s);document.querySelectorAll('[data-key]').forEach(el=>{el.setAttribute('aria-invalid',bad.includes(el.dataset.key)?'true':'false');});
 const alerts=[...a.urgent];if(bad.length)alerts.push('數值超出本工具合理範圍：'+bad.map(k=>labels[k]).join('、')+'；請核對單位。');if(num(s,'age')!==null&&!a.adult)alerts.push('未滿18歲：請使用兒科專用高血鈉處置；本工具不產生治療速度。');
 document.querySelector('#alert').innerHTML=alerts.length?note(alerts.map(t=>`<p>${esc(t)}</p>`).join(''),'danger'):'';
 const missing=a.blocks;document.querySelector('#summary').innerHTML=`<h2>即時判讀</h2><div class="big">${fmt(num(s,'na'),0)} <span class="unit">mmol/L</span></div><p>${num(s,'na')===null?'尚未輸入血鈉':a.high?(num(s,'na')>155?'重度高血鈉':num(s,'na')>150?'中度高血鈉':'輕度高血鈉'):'目前未達高血鈉定義'}</p>${a.corrected?`<p class="small">血糖校正Na：${fmt(a.corrected[0])}–${fmt(a.corrected[1])}<br>係數1.6–2.4；不直接代入補水速度。</p>`:''}${a.tonicity!==null?`<p class="small">估計有效滲透壓 ${fmt(a.tonicity)} mOsm/kg<br>2×Na＋glucose/18（不含BUN）</p>`:''}<hr>${missing.length?`<strong>補水速度暫緩：待確認事項</strong><ul class="small">${missing.slice(0,8).map(t=>`<li>${esc(t)}</li>`).join('')}</ul>${missing.length>8?`<p class="small">另有 ${missing.length-8} 項，詳見補水計畫。</p>`:''}`:`<strong>可進入補水估算</strong><p class="small">補齊持續流失與給水量後，產生暫定補水速度。</p>`}<hr><p class="small">${esc(treatment(a))}</p><p class="small">所有數值需依抽血結果調整。</p>`;
 if(step===1){document.querySelector('#causes').innerHTML=a.high?a.causes.map(c=>`<article class="reason"><h3>${esc(c.title)}</h3><p>${esc(c.evidence)}</p><p class="hint">下一步：${esc(c.next)}</p></article>`).join(''):'<p class="empty">先輸入血清Na，確認高血鈉後進行分析。</p>';if(a.efwc!==null)document.querySelector('#causes').innerHTML+=note(`<strong>尿液EFWC：${fmt(a.efwc,0)} mL/day</strong><p>${a.efwc>0?'正值支持腎臟持續流失自由水。':'零或負值表示此量測期間沒有正的尿液自由水流失；仍需評估其他失水。'}</p>`);if(num(s,'una')!==null)document.querySelector('#causes').innerHTML+=`<p class="hint">尿Na ${fmt(num(s,'una'),0)}：${num(s,'una')<20?'支持保鈉反應／低容量，但需配合臨床。':'利尿劑、滲透性利尿與腎病時，即使低容量也可能偏高。'}</p>`;if(s.flags.includes('brain'))document.querySelector('#causes').innerHTML+=note('腦傷／手術可能涉及AVP缺乏，需評估低張性多尿；若為目標性高血鈉，遵循神經重症專科目標。','warn');if(num(s,'serumOsm')!==null&&a.high&&num(s,'serumOsm')<290)document.querySelector('#causes').innerHTML+=note('血Na與實測滲透壓可能不一致，請複查直接ISE（如血氣Na）、檢體與低蛋白造成的偽高血鈉。','warn');}
 if(step===2){document.querySelector('#factorHint').textContent=`TBW係數 ${fmt(a.f,2)}；估計TBW ${fmt(a.tbw)} L。男性0.6、女性0.5；≥65歲各下修0.05。肥胖／明顯脫水需由醫師調整係數。`;
 document.querySelector('#waterMetrics').innerHTML=`<div class="metrics"><div class="metric"><span>補至Na 140的總自由水缺損</span><strong>${fmt(a.deficit)} L</strong></div><div class="metric"><span>首24小時目標Na</span><strong>${fmt(p.target)} <span>mmol/L</span></strong></div></div><p class="hint">首24小時僅矯正所需的淨水量：約 ${fmt(p.base,0)} mL（未含持續流失）。目標不低於145；總缺損不能一次輸完。</p>`;
 document.querySelector('#efwcControl').innerHTML=a.efwc!==null?`<p class="hint">尿液EFWC ${fmt(a.efwc,0)} mL/day。${a.efwc>=0?'<button class="link-action" id="useEFWC">將此估值帶入尿液自由水流失</button>':'負值不自動當作負流失帶入；請個別判斷。'}</p>`:'<p class="hint">若要估尿液EFWC，請在原因分析補齊尿量、尿Na與尿K。</p>';
 const missingLoss=p.missing.map(k=>labels[k]);let result='';
 if(a.blocks.length)result+=note(`<strong>暫不產生例行補水速度</strong><ul class="warning-list">${a.blocks.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`,'warn');
 if(missingLoss.length)result+=note('持續流失／給水仍缺：'+missingLoss.join('、')+'。填0需已確認，勿將未知量當0。','warn');
 if(s.lossReviewed!=='yes')result+=`<p class="hint">請確認持續流失與既有給水量。</p>`;
 if(p.net!==null&&p.net<0)result+=note('目前其他已提供自由水超過本模型所需總量；需重新評估既有給水與矯正速度，不產生負輸液速度。','warn');
 if(p.eligible&&s.route==='d5w')result+=`<div id="rateBox" class="notice"><strong>D5W 約 ${fmt(p.rate,0)} mL/hr</strong><p>首24小時追加自由水約 ${fmt(p.net,0)} mL。這是起始估算，並非固定醫囑。</p></div>`;
 else if(p.eligible&&s.route==='enteral')result+=note(`<strong>追加口服／管灌自由水約 ${fmt(p.net,0)} mL／24小時</strong><p>平均 ${fmt(p.rate,0)} mL/hr僅表示總量換算；依吞嚥安全與耐受分次給水。</p>`);
 else if(p.eligible&&s.route==='half')result+=note('0.45% NaCl含Na約77 mmol/L，非100%自由水；加入K也會改變鈉反應。本頁不把自由水量直接換成此輸液速度，需另用Na＋K平衡模型及實測Na調整。','warn');
 else if(p.eligible)result+=note('請選擇給水途徑。');
 if(s.duration==='acute'&&s.flags.includes('sodium'))result+=note('急性鈉負荷且有症狀時，文獻描述初期可下降1–2 mmol/L/hr；需在重症／專科監督下執行。本頁保守計算不適用於該快速矯正路徑。','warn');
 result+=`<h3 class="guide-title">治療與監測</h3><p>${esc(treatment(a))}</p><ul><li>初期每2–4小時複測Na；每次複測重估速度、輸入及尿量。</li><li>D5W需監測血糖；同步處理低K、高Ca、發燒與致病用藥。</li><li>尿崩症確診後按病因治療；DDAVP後尿量可迅速下降，原補水速度需重新評估。</li><li>AKI／少尿、肺水腫或補水無法進行時，評估腎臟科會診與RRT；需RRT且鈉矯正需精細控制時可考慮CRRT，透析液Na應個別設定。</li></ul>`;document.querySelector('#planResult').innerHTML=result;}
 if(step===3)renderTracking();
}
function taipei(ms){return new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(ms));}
function nowInput(){const f=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date());return f.replace(' ','T');}
function renderTracking(){const t=trend(s,logs);let html='';if(!s.baselineTime||num(s,'na')===null)html='<p class="empty">請先輸入基本評估Na與起始採血時間。</p>';else if(t.invalid)html=note(t.warnings.map(x=>`<p>${esc(x)}</p>`).join(''),'warn');else if(!logs.length)html='<p class="empty">尚無追蹤資料；加入第一次追蹤以計算區間速度。</p>';else{
 if(t.warnings.length)html+=note(t.warnings.map(x=>`<p>${esc(x)}</p>`).join(''),'warn');
 const pts=t.points,min=Math.min(...pts.map(x=>x.na),145)-2,max=Math.max(...pts.map(x=>x.na))+2,span=pts.at(-1).time-pts[0].time;
 const x=i=>55+(i.time-pts[0].time)/span*590,y=n=>185-(n-min)/(max-min)*150;
 html+=`<svg class="chart" viewBox="0 0 700 220" role="img" aria-label="血鈉追蹤趨勢，詳細數值見下方表格"><line x1="55" x2="645" y1="${y(145)}" y2="${y(145)}" stroke="#b2c5e8" stroke-dasharray="5 5"/><text x="12" y="${y(145)+4}">145</text><polyline fill="none" stroke="#1255ef" stroke-width="3" points="${pts.map(i=>`${x(i)},${y(i.na)}`).join(' ')}"/>${pts.map(i=>`<circle cx="${x(i)}" cy="${y(i.na)}" r="4" fill="#1255ef"/><text x="${x(i)}" y="${y(i.na)-12}" text-anchor="middle">${i.na}</text>`).join('')}<text x="55" y="210">起始</text><text x="645" y="210" text-anchor="end">${fmt(span/3600000)} 小時</text></svg>`;
 html+=`<div class="table-wrap"><table><thead><tr><th>台灣採血時間</th><th>Na</th><th>區間下降／hr</th><th>起始累積下降</th><th class="no-print">操作</th></tr></thead><tbody><tr><td>${taipei(pts[0].time)}（起始）</td><td>${pts[0].na}</td><td>—</td><td>0</td><td></td></tr>${t.intervals.map(i=>`<tr><td>${taipei(i.time)}</td><td>${i.na}</td><td>${fmt(i.rate,2)}</td><td>${fmt(i.drop)}</td><td class="no-print"><button data-delete="${i.time}">移除</button></td></tr>`).join('')}</tbody></table></div><p class="hint">區間下降＝(前次Na−本次Na)／實際間隔。負值代表Na上升；不以短區間外推整日下降量。≤24小時警示僅涵蓋已有採血點，不代表連續監測。</p>`;
 }document.querySelector('#trendResult').innerHTML=html;
 const a=analyze(s),p=plan(s);document.querySelector('#clinicalReport').innerHTML=`<h3 class="guide-title">評估摘要</h3><p>起始Na ${esc(s.na||'未填')} mmol/L；${esc(s.age||'未填')}歲、${esc(s.weight||'未填')} kg。發生時間：${{acute:'48小時內',chronic:'超過48小時',unknown:'不明'}[s.duration]||'未填'}。</p><p>總自由水缺損 ${fmt(a.deficit)} L；首24小時目標Na ${fmt(p.target)} mmol/L。${p.eligible&&s.route==='d5w'?`暫定D5W ${fmt(p.rate,0)} mL/hr（須實測調整）。`:'目前未產生可執行的D5W速度。'}</p><p>${esc(treatment(a))}</p>${a.high?a.causes.map(c=>`<p><strong>${esc(c.title)}：</strong>${esc(c.evidence)} ${esc(c.next)}</p>`).join(''):''}<p class="hint">初期每2–4小時複測Na，監測血糖、尿量與神經狀態。摘要隨基本評估參數更新；追蹤中請勿任意覆蓋起始Na。</p>`;
}
document.addEventListener('input',e=>{const k=e.target.dataset.key;if(k&&e.target.type!=='radio'){s[k]=e.target.value;update();}});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.key){s[el.dataset.key]=el.value;update();}if(el.dataset.flag){s.flags=el.checked?[...s.flags,el.dataset.flag]:s.flags.filter(k=>k!==el.dataset.flag);update();}if(el.id==='demo'&&el.value){const base={age:'75',weight:'60',sex:'female',na:'160',glucose:'110',cr:'1.0',egfr:'60',sbp:'120',renal:'stable',duration:'unknown',volume:'hypo',hemo:'stable',neuro:'no',intentional:'no',urine:'1200',uosm:'900',una:'10',uk:'30',drop:'8',insensible:'700',giLoss:'0',urineLoss:'900',intake:'0',lossReviewed:'yes',route:'d5w',flags:['poorIntake']};if(el.value==='di')Object.assign(base,{urine:'6000',uosm:'150',una:'10',uk:'10',volume:'eu',flags:['brain'],urineLoss:''});if(el.value==='shock')Object.assign(base,{hemo:'shock',sbp:'75',renal:'aki',urine:'250',flags:['gi'],giLoss:''});if(el.value==='sodium')Object.assign(base,{duration:'acute',volume:'hyper',neuro:'yes',flags:['sodium'],na:'170'});s=base;logs=[];render();}});
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.step!==undefined){step=Number(el.dataset.step);render();}if(el.dataset.nav){step+=el.dataset.nav==='next'?1:-1;render();window.scrollTo({top:0,behavior:'smooth'});}if(el.id==='reset'){if(confirm('清除所有輸入與追蹤資料？')){s={...defaults,flags:[]};logs=[];step=0;render();}}if(el.id==='useEFWC'){s.urineLoss=String(Math.round(analyze(s).efwc));render();}if(el.id==='now')document.querySelector('#logTime').value=nowInput();if(el.id==='addLog'){const time=document.querySelector('#logTime').value,raw=document.querySelector('#logNa').value,na=Number(raw),ms=Date.parse(time+'+08:00'),base=Date.parse(s.baselineTime+'+08:00');let error='';if(!s.baselineTime||!Number.isFinite(base)||num(s,'na')===null)error='先填起始Na與起始採血時間。';else if(!time||!raw||!Number.isFinite(ms)||na<100||na>220)error='請填正確採血時間與Na（100–220）。';else if(ms<=base)error='追蹤時間須晚於起始採血時間。';else if(ms>Date.now()+60000)error='採血時間不可在未來；請核對台灣時間。';else if(logs.some(l=>l.time===time))error='已有相同時間的追蹤，請先移除舊值再新增。';if(error)document.querySelector('#logError').textContent=error;else{logs.push({time,na});render();}}if(el.dataset.delete){logs=logs.filter(l=>Date.parse(l.time+'+08:00')!==Number(el.dataset.delete));render();}if(el.id==='print')window.print();});
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'read_hypernatremia_assessment',description:'Read the current patient inputs, cause analysis, missing conditions, and provisional water plan without changing data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected empty object');const p=plan(s);return {sodium:num(s,'na'),causes:p.causes,missing:p.blocks,provisionalD5WRate:s.route==='d5w'?p.rate:null};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
render();
